### ISSUE TITLE
Cards are blurry, pixel drawing seems off

### ISSUE THREAD

**Issue by arthurquinn** [arthurquinn/solitaire#36]
Figure out why the pixels seem blurry on the canvas. Must have something to do with the pixel x pixel size of the canvas vs the card.

**Comment by arthurquinn** [comment]
The issue here was the element size (actual DOM size of the canvas) was larger than the internal (drawing area) canvas size. When they are matched, the drawn image are scaled 1:1.

**Comment by MSaIim** [comment]
If you want better looking sprites: [https://opengameart.org/content/boardgame-pack](https://opengameart.org/content/boardgame-pack). It comes with sounds, spritesheets, and individual images. License is public domain as well (you can see license info on the left side on the site).
