### ISSUE TITLE
Bug in resetting stock after last draw

### ISSUE THREAD

**Issue by arthurquinn** [arthurquinn/solitaire#41]
When the stock needs to be refreshed from the talon, the client is receiving a pop x cards from pile 0 and push x cards to pile 1. In this instance of the draw command, it must be pop from talon (1) and to stock(0).

![bug](https://user-images.githubusercontent.com/26178797/31063744-c6b1858c-a703-11e7-9124-fb06341af30b.png)

As is seen in the above image, while the stock has cards, the draw command is correct. We are popping 3 from the stock and adding 3 to the talon. However, when the stock is empty and it is time to refresh the stock, here we are popping 24 from the stock and pushing 24 to the talon, this should be reversed.

**Comment by MSaIim** [comment]
Fixed.
